### ISSUE TITLE
Any Plan for Android TV app ?

### ISSUE THREAD

**Issue by xVoldx** [hyugogirubato/Kamyroll#1]

**Comment by hyugogirubato** [comment]
Hi! For TVs I personally do not own android TV allowing me to do tests. The app is "blocked" in portrait mode for a better graphical interface, but I will look to potentially make a version in landscape mode in order to make the experience more enjoyable on tablet.

**Comment by hyugogirubato** [comment]
@xVoldx Since update 1.3.0, the app is now compatible in portrait mode and for android TVs.
