### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by MaiSan0001** [hyugogirubato/Kamyroll#5]
Hello i really want run Kamyroll on windows and I'm no expert with android studio (no experience) , im asking if there is a way run on Android Studio. Thanks!

**Comment by hyugogirubato** [comment]
There are several ways to run the application on windows (before the release of windows 11 lol). You can use an emulator that you will often find free on the internet, but in your question you want to make it work with android studio. So on android studio there is indeed an integrated android emulator, so you can run the app with it. To do this you must first download the apk associated with the GPU version of the emulator (often x86), then once the .apk file is on your computer, you launch the android emulator. Once it's loaded, you just have to drag the apk file into the emulator window and it will install the app for you. NOTE: you can also download the app from the emulator with the android browser.
