### ISSUE TITLE
Kamyroll on LineageOS without Gapps

### ISSUE THREAD

**Issue by Feripe-a** [hyugogirubato/Kamyroll#9]
I've flashed [LineageOS](https://lineageos.org/) without any [Google Apps](https://wiki.lineageos.org/gapps.html) on my phone pretty recently. I've installed Kamyroll and it didn't open — the app crashes whenever I open it. It must've something to with my phone lacking Google Apps — it's known that apps break without Google Apps. Crunchyroll works without them, which is strange as your app is based on it, right? I've installed [MicroG](https://microg.org/) hoping Kamyroll would work but it did not.
Is it possible to fix? I totally understand you if it is impossible. If so happens that the crashing is unfixable, it's good to note somewhere that Kamyroll does not work on LineageOS without Gapps.

**Comment by hyugogirubato** [comment]
In relation to your problem, I can tell you that it is the lack of google play service (the apk) that causes the application to crash. The services are used for the premium bypass to access the database, however I read that it was possible to remove them but during my last try I couldn't get the app to work, so I got them have left for the moment. I will try to remove them again, but I do not promise anything.

**Comment by Feripe-a** [comment]
Thanks for your time, as I said, I totally understand if it is unfixable.

**Comment by Feripe-a** [comment]
I've been thinking about it. I think it's better to let it go. It will be pretty difficult to maintain your project without using Google Play apps. Yesterday I've got Kamyroll Python working, thanks to you and OrigamiK. I'll from now on download anime on my computer, move to my phone and watch there.
I'm sorry that I wasted your time. Could please note that Kamyroll won't work without Google Play apps on Custom Roms like LineageOS?

**Comment by Feripe-a** [comment]
With the above said, I'm closing this "issue"
I'm really sorry that made your waste your precious time.
